name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes com relatório
        run: npm run test:report

      - name: Salvar artefatos (vídeos e screenshots)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots

      - name: Salvar relatório HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-html
          path: cypress/reports/html
